# Generated by Django 5.2.5 on 2025-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_timetablesettings_alter_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetablesettings',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetablesettings',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timetablesettings',
            name='period_times',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='short_break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='short_break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
